#ifndef APP_TITLE
#define APP_TITLE "ste"
#endif

#ifndef BACKGROUND_OPACITY
#define BACKGROUND_OPACITY 0.8
#endif

#ifndef SCROLLBACK_SIZE
#define SCROLLBACK_SIZE 50000
#endif

#ifndef MODIFIER_MASK_COMMON
#define MODIFIER_MASK_COMMON GDK_CONTROL_MASK | GDK_SHIFT_MASK
#endif
#ifndef KEYVAL_COPY_CLIPBOARD
#define KEYVAL_COPY_CLIPBOARD "y"
#endif
#ifndef KEYVAL_PASTE_CLIPBOARD
#define KEYVAL_PASTE_CLIPBOARD "p"
#endif
